Error serving client: /home/ted/proiect/pythonWorker.cpp(131): Throw in function std::string pythonEval(std::string)
Dynamic exception type: boost::exception_detail::clone_impl<pythonError>
[tag_string_info*] = Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'i' is not defined


Error serving client: /home/ted/proiect/pythonWorker.cpp(131): Throw in function std::string pythonEval(std::string)
Dynamic exception type: boost::exception_detail::clone_impl<pythonError>
[tag_string_info*] = Traceback (most recent call last):

  File "<string>", line 1, in <module>

TypeError: get() takes no keyword arguments


Error serving client: /home/ted/proiect/pythonWorker.cpp(131): Throw in function std::string pythonEval(std::string)
Dynamic exception type: boost::exception_detail::clone_impl<pythonError>
[tag_string_info*] = Traceback (most recent call last):

  File "<string>", line 1, in <module>

TypeError: get() takes no keyword arguments


Error serving client: /home/ted/proiect/request.cpp(214): Throw in function Request RequestParser::getRequest()
Dynamic exception type: boost::exception_detail::clone_impl<httpParseError>
[tag_string_info*] = HTTP method  not recognized.

